global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

rule_files:
  - "alert.rules"

scrape_configs:

  - job_name: alert_exporter
    scrape_interval: 5s
    static_configs:
    - targets:
      - "alert_exporter:9000"
